### ISSUE TITLE
Failed to Load Python Module

### ISSUE THREAD

**Issue by gabaroar** [Komodo/komodo-go#17]
I get the following error when trying to use the plug-in.  

System Info:
OS: Linux Mint 17
Komodo Version: Komodo Edit, version 8.5.4, build 14424, platform linux-x86_64.
Komodo-Go: 1.3.1

    Failed to load the Python module: '/home/jason/.komodoedit/8.5/XRE/extensions/golang@activestate.com/components/koGoLanguage.py'

    Traceback (most recent call last):
      File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/server/loader.py", line 134, in loadModule
        return self._getCOMModuleForLocation(aLocalFile)
      File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/server/loader.py", line 158, in _getCOMModuleForLocation
        py_mod = loader.load_module( module_name_in_sys, stuff )
       File "/home/jason/Komodo-Edit-8/lib/python/lib/python2.7/ihooks.py", line 272, in load_module
    m = self.hooks.load_source(name, filename, file)
      File "/home/jason/Komodo-Edit-8/lib/python/lib/python2.7/ihooks.py", line 170, in load_source
        return imp.load_source(name, filename, file)
      File "/home/jason/.komodoedit/8.5/XRE/extensions/golang@activestate.com/components/koGoLanguage.py", line 27, in <module>
        class koGoLanguage(KoLanguageBase, KoLanguageBaseDedentMixin):
      File "/home/jason/.komodoedit/8.5/XRE/extensions/golang@activestate.com/components/koGoLanguage.py", line 35, in koGoLanguage
    [components.interfaces.koIInterpolationCallback]
      File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/components.py", line 103, in __getattr__
        return self._get_one(attr)
      File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/components.py", line 153, in _get_one
        raise xpcom.COMException(nsError.NS_ERROR_NO_INTERFACE, "The interface '%s' does not exist" % name,))
    <class 'xpcom.Exception'>: 2147500034 (The interface 'koIInterpolationCallback' does not exist)

**Comment by toddw-as** [comment]
Ah, sorry about that - that piece of code won't work on Komodo 8 (it was written for Komodo 9)- I'll have to add a check for that.

**Comment by toddw-as** [comment]
Fixed with commit d28a11cf.

**Comment by gabaroar** [comment]
I have installed 1.3.2 and I am receiving the same error.

Failed to load the Python module: '/home/jason/.komodoedit/8.5/XRE/extensions/golang@activestate.com/components/koGoLanguage.py'

Traceback (most recent call last):
  File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/server/loader.py", line 134, in loadModule
    return self._getCOMModuleForLocation(aLocalFile)
  File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/server/loader.py", line 158, in _getCOMModuleForLocation
    py_mod = loader.load_module( module_name_in_sys, stuff )
  File "/home/jason/Komodo-Edit-8/lib/python/lib/python2.7/ihooks.py", line 272, in load_module
    m = self.hooks.load_source(name, filename, file)
  File "/home/jason/Komodo-Edit-8/lib/python/lib/python2.7/ihooks.py", line 170, in load_source
    return imp.load_source(name, filename, file)
  File "/home/jason/.komodoedit/8.5/XRE/extensions/golang@activestate.com/components/koGoLanguage.py", line 27, in <module>
    class koGoLanguage(KoLanguageBase, KoLanguageBaseDedentMixin):
  File "/home/jason/.komodoedit/8.5/XRE/extensions/golang@activestate.com/components/koGoLanguage.py", line 35, in koGoLanguage
    [components.interfaces.koIInterpolationCallback]
  File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/components.py", line 103, in __getattr__
    return self._get_one(attr)
  File "/home/jason/Komodo-Edit-8/lib/mozilla/python/xpcom/components.py", line 153, in _get_one
    raise xpcom.COMException(nsError.NS_ERROR_NO_INTERFACE, "The interface '%s' does not exist" % (name,))
<class 'xpcom.Exception'>: 2147500034 (The interface 'koIInterpolationCallback' does not exist)

**Comment by toddw-as** [comment]
Discovered the problem, fixed in 1.3.3:
https://github.com/Komodo/komodo-go/releases
